### ISSUE TITLE
Scène Home : Chambres et lits

### ISSUE THREAD

**Issue by AlexDmr** [AlexDmr/ccbl-gfx-angular-dev#10]
Dans les chambres, il y a deux zones :
  - chambres
  -lit
Un personnage peut être dans la chambre mais pas dans le lit.
Si un personnage est dans le lit, cela implique qu'il est dans la chambre.

Idée de solution
2 observables pour chaque chambre
  - présenceDansChambresMaisPasLit
  - présenceDansLit

de là on dérive un observable présenceDansChambre = combineLatest(présenceDansChambresMaisPasLit, présenceDansLit).pipe(
  map( (b1, b2) => b1 || b2 
)

voir [https://rxjs-dev.firebaseapp.com/api/operators/combineLatest](url)

**Comment by Badzi007** [comment]
c'est fait,
pour le mapping  c'est pas 2 variable que je reçois mais un tableau de variable et donc j'ai mis 
`pipe(map( (b1) => b1[0] || b1[1])`

**Comment by AlexDmr** [comment]
Ça marche, ou bien

pipe(map( ( [a, b] ) => a || b) )
