### ISSUE TITLE
Scène Home : Personnages dans couloir 2

### ISSUE THREAD

**Issue by AlexDmr** [AlexDmr/ccbl-gfx-angular-dev#11]
Il manque la possibilité de placer des personnages dans couloir 2.

**Comment by AlexDmr** [comment]
J'ajoute qu'il faut ajouter un interupteur et une lampe (peut être élargir un peu le couloir si pas assez de place)

**Comment by Badzi007** [comment]
c'est fait.
j'ai finalement pas eu besoin d'élargir le couloir

**Comment by AlexDmr** [comment]
La taille du couloir se révèle être bonne en effet.
Par contre il faudrait aligner les personnage dans le sens vertical, sinon cela déborde sur la chambre quand il y a deux personnage dans le couloir.

**Comment by Badzi007** [comment]
c'est fait.
