### ISSUE TITLE
Scène Home : Salon et canapé

### ISSUE THREAD

**Issue by AlexDmr** [AlexDmr/ccbl-gfx-angular-dev#12]
Dans le salon, il doit être possible d'être sur la canapé ou pas et d'être dans le salon ou pas => 2 zones.
De la même façon que pour les chambres et les lits, la présence sur le canapé implique la présence dans le salon.
(voir #10 )

**Comment by Badzi007** [comment]
c'est fait

**Comment by AlexDmr** [comment]
Quelques petites corrections :
  - La zone canapée est nommée Living Room => Nommer cette zone Sofa
  - Agrandir la zone Sopha pour que ça englobe tout le sofa.
  - Il n'y a pas de nom pour la zone Salon => Living Room
  - La  zone salon est tout en bas de la pièce, il faudrait la placer sur la partie droite de la pièce. A gauche ou trouverais le sofa et la TV + volume. Interrupteur peut être à déplacer si il est recouvert par des personnages.

**Comment by Badzi007** [comment]
c'est fait.
