### ISSUE TITLE
Scène Home : Machine à café

### ISSUE THREAD

**Issue by AlexDmr** [AlexDmr/ccbl-gfx-angular-dev#13]
Sur la base de la machine à café, indiquer l'état avec un texte (OFF, ON,  ONGOING, READY)

**Comment by Badzi007** [comment]
d'accord normalement il y a une différence entre chaque état au format GIF je sais pas si ça se vois ou pas assez

**Comment by AlexDmr** [comment]
ça se voit mais pas assez, l'idée est aussi de pouvoir lire l'état car ça correspondra surement à des valeurs dans CCBL.

**Comment by Badzi007** [comment]
C'est fait j'ai mis a la place de ONGOING ->PREPARING qui me semble plus significatif mais je peux toujours modifier si vous préférer ONGOING
