### ISSUE TITLE
Bugs Heating system : horloge

### ISSUE THREAD

**Issue by AlexDmr** [AlexDmr/ccbl-gfx-angular-dev#2]
Lorsque l'heure est modifiée via le champs texte, les aiguilles du cadran (minute et heure) ont un comportement ératique.

**Comment by AlexDmr** [comment]
Autre chose, il faudrait une représentation jour/nuit associé à l'horloge (par exemple un soleil le jour et un croissant de lune la nuit)

**Comment by Badzi007** [comment]
probleme horloge resolue + ajout de la representation jour/nuit fait

**Comment by AlexDmr** [comment]
Problème surcharge CPU avec l'horloge codée dans cs-canvas-clock
Observation :
la page est affichée, j'ouvre le gestionnaire de tâche pour voir la charge CPU et mémoire, au bout de 10-20 secondes, la page occupe 100% d'un CPU.
Observation 2 : Si je commente la balise cs-canvas-clock, alors la charge CPU tend vers 0 au bout de quelques secondes et y reste.

**Comment by Badzi007** [comment]
performance améliorer et mis a jour dans la branche Ismail_iteration1.
serait il possible de confirmé par rapport au performance?

**Comment by AlexDmr** [comment]
je ne relève plus de problème de performance, par contre, à chaque seconde, le cadran s'efface et se réaffiche, provoquant un effet de clignotement;
Le CPU est chargé à 8% environs (sur un CPU), ce qui me laisse penser qu'il y a destruction/création toute les secondes.

**Comment by AlexDmr** [comment]
au passage il faut commenter ou supprimer la ligne 105
`this.openWindows.next(Day);`

les volets doivent être pilotés par CCBL

**Comment by AlexDmr** [comment]
Dernière remarque de test, si je change l'heure via l'horloge numérique un grand nombre de fois (je me place sur les minute et je maintient la touche HAUT appuyé) alors la charge CPU monte à 100% et quand je relache elle se maintient à 50% d'un CPU environs.
Ca ne se produit que si la balise cs-canvas-clock est présente

**Comment by Badzi007** [comment]
modification effectué avec différente mise a jour pour améliorer les performance.
