### ISSUE TITLE
Scène Maison

### ISSUE THREAD

**Issue by AlexDmr** [AlexDmr/ccbl-gfx-angular-dev#7]
Problème lorsque je scrolle vers le bas, ça remonte automatiquement au début de page.
Reproduction du bug
  - chargement de la page
  - aller sur l'onglet Home detail
  - Démarrer le programme CCBL
  - passer en mode nuit en réglant l'horlage
  - la vidéo démarre, si on scrolle vers le bas ça nous ramène toujours en haut

Si on repasse en mode jour, le problème persiste.
Avant de passer en mode nuit , le problème ne se manifeste pas.

**Comment by Badzi007** [comment]
c'est un problème au niveau du composant horloge il existe aussi dans scène heating je vais y travailler pour le résoudre le plus tôt possible

**Comment by Badzi007** [comment]
pour la reproduction du problème il faut se mettre sur l'horloge Electronique pour éventuellement modifier l'heure comme la valeur elle change automatiquement et qu'il y a dessus le curseur ça fait automatiquement le focus quand le valeur change .
je vais regarder si il y a moyen de désactiver le focus

**Comment by Badzi007** [comment]
après plusieurs recherche je remarque que le problème est uniquement sur google chrome qui semble interpréter de cette manière et donc on a 2 solution a ca:
-solution 1: désactiver le scrolling tant que le curseur est en focus sur le champs input d'heure
-solution 2:  désactiver l'auto-incrémentation d'heure  tant que le curseur est en focus sur le champs input d'heure
sinon on peux toujours laisser le système comme il est maintenant vu que la modification d'heure est uniquement pour tester les fonctionnalité en développement

**Comment by AlexDmr** [comment]
On peut s'abonner au scroll sur la fenêtre je pense.
Si focus sur inputClockalors abonnement sur scroll
Si scroll pendant abonnement, alors inputClock.blur()
Si blur sur inputClock alors désabonnement du scroll

**Comment by Badzi007** [comment]
si on fait cette méthode ça risque de mal fonctionner avec Microsoft Edge qui interprète de cette maniéré 
![image](https://user-images.githubusercontent.com/55756504/84499335-ae7ff900-acb2-11ea-8861-3b0e601b82a8.png)

**Comment by Badzi007** [comment]
c'est bon j'ai tester une solution sur les 3 navigateur et ça fonctionne correctement 
j'ai ajouter a l'input `(scroll)="onScroll($event)`
et mettre la méthode
dans la méthode  
```
  onScroll(event) {
    this.clock.nativeElement.blur();
  }

```
